version: '3.8'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/var/log/redis
    networks:
      redis-net:
        ipv4_address: 172.20.0.10

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-slave-data-1:/data
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.11
    depends_on:
      - redis-master

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-slave-data-2:/data
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.12
    depends_on:
      - redis-master

  redis-sentinel:
    image: redis:latest
    container_name: redis-sentinel
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --sentinel
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.13
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
  redis-sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.14
  redis-sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-net:
        ipv4_address: 172.20.0.15
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "6390:6379"
    networks:
      redis-net:
        ipv4_address: 172.20.0.20
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

volumes:
  redis-master-data:
  redis-slave-data-1:
  redis-slave-data-2:

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

